kind: pipeline
type: kubernetes
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive --remote

- name: docker  
  image: banzaicloud/drone-kaniko
  settings:
    repo: perl/perlweb
    registry: harbor.ntppool.org
    # auto_tag doesn't work if we also set other tags..
    #tags: latest,${DRONE_COMMIT_SHA}
    auto_tag: true
    cache: true
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password
